// Generated by CoffeeScript 1.7.1
(function() {
  var dispatch, instrumentor, modules, root;

  instrumentor = require('instrumentor');

  modules = {};

  dispatch = function(message, spark) {
    var req;
    req = message.action;
    if (!modules[req]) {
      modules[req] = instrumentor.instrument(req);
    }
    return modules[req](message).then(function(result) {
      return spark.send('response', {
        request: req,
        result: result
      });
    }).fail(function(error) {
      return spark.send('error', {
        request: req,
        error: error
      });
    }).progress(function(update) {
      return spark.send('progress', {
        request: req,
        update: update
      });
    });
  };

  root = function(path) {
    return instrumentor.root = path;
  };

  module.exports = {
    dispatch: dispatch,
    root: root
  };

}).call(this);
